version: '3.8'
services:
  server:
    # restart: always
    build: server
    container_name: id37bot
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    network_mode: "host"
    environment:
      - TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN